//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizBee.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public Answer()
        {
            this.AnswerImages = new HashSet<AnswerImage>();
            this.QuestionAnswers = new HashSet<QuestionAnswer>();
            this.QuestionOptions = new HashSet<QuestionOption>();
        }
    
        public int AnswerID { get; set; }
        public string AnswerDesc { get; set; }
    
        public virtual ICollection<AnswerImage> AnswerImages { get; set; }
        public virtual ICollection<QuestionAnswer> QuestionAnswers { get; set; }
        public virtual ICollection<QuestionOption> QuestionOptions { get; set; }
    }
}
