//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizBee.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionImage
    {
        public int ImageID { get; set; }
        public int QuestionID { get; set; }
        public string ImageURL { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
