//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizBee.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.QuestionAnswers = new HashSet<QuestionAnswer>();
            this.QuestionImages = new HashSet<QuestionImage>();
            this.QuestionOptions = new HashSet<QuestionOption>();
        }
    
        public int QuestionID { get; set; }
        public string QuestionDesc { get; set; }
        public int QuestionOrder { get; set; }
        public string AnswerExplanation { get; set; }
    
        public virtual ICollection<QuestionAnswer> QuestionAnswers { get; set; }
        public virtual ICollection<QuestionImage> QuestionImages { get; set; }
        public virtual ICollection<QuestionOption> QuestionOptions { get; set; }
    }
}
