//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizBee.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserQuiz
    {
        public int QuizUserID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> datetimecompleted { get; set; }
        public Nullable<int> Score { get; set; }
        public int QuizCategoryID { get; set; }
    
        public virtual QuizCategory QuizCategory { get; set; }
    }
}
